# Azure DevOps Pipeline for Backend Deployment
trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  azureServiceConnection: 'your-azure-service-connection'
  appServiceName: 'your-hr-onboarding-backend'
  resourceGroupName: 'your-resource-group'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python -m pytest tests/ -v
      displayName: 'Run tests'
      continueOnError: true

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(appServiceName)'
              package: '$(System.DefaultWorkingDirectory)'
              appSettings: |
                -PYTHONPATH "$(System.DefaultWorkingDirectory)"
                -WEBSITE_PYTHON_DEFAULT_VERSION "3.11"
                -SCM_DO_BUILD_DURING_DEPLOYMENT "true"
