name: Deploy Frontend (Azure Static Web Apps)

on:
  push:
    branches:
      - master
  
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_frontend.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Add this secret in Step 4
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend        # your React app folder
          output_location: dist         # Vite build output folder
        env:
          # Add this secret in Step 5
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
