name: Deploy Backend (FastAPI) to Azure App Service

on:
  push:
    branches: [ "master" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy_backend.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Vendor dependencies into .python_packages so the server doesn't need pip
      - name: Install production dependencies into .python_packages
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages

      # Zip ONLY backend contents (exclude venv, git, and .deployment)
      - name: Create deployment artifact (zip)
        working-directory: backend
        run: |
          zip -r ../backend.zip . \
            -x "__pycache__/*" ".venv/*" ".git/*" ".deployment"

      - name: Deploy to Azure Web App (Zip Deploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: vabackend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_VABACKEND }}
          package: backend.zip
